version: '3.1'
services:
  bomberos:
    build: .
    image: bomberos-back
    volumes:
      - '.:/app'
    container_name: bomberos-back
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8013:8000
