# Generated by Django 4.1.2 on 2023-04-25 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrada', models.DateField(auto_now_add=True)),
                ('horaEntrada', models.TimeField(auto_now_add=True)),
                ('fechaSalida', models.DateField(blank=True, null=True)),
                ('horaSalida', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='turnos', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guardias', to='guardias.estadoguardia')),
            ],
        ),
    ]
