# Generated by Django 3.2 on 2024-05-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.bombero')),
                ('bombero_cerro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bombero_cerro', to='usuarios.bombero')),
            ],
        ),
        migrations.CreateModel(
            name='GuardiaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.actividad')),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardias.guardia')),
            ],
        ),
    ]
