# Generated by Django 4.1.2 on 2023-04-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0004_actividad_detallecategoria'),
        ('guardias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guardias', to='bomberos.actividad')),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles', to='guardias.guardia')),
            ],
        ),
    ]
