# Generated by Django 3.2 on 2024-05-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardiaactividad',
            name='guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardia_actividad', to='guardias.guardia'),
        ),
    ]
