# Generated by Django 4.1.2 on 2023-04-27 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guardias', '0002_detalleguardia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='bombero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guardias', to=settings.AUTH_USER_MODEL),
        ),
    ]
