# Generated by Django 4.1.2 on 2023-04-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0005_alter_actividad_descripcion'),
        ('guardias', '0003_alter_guardia_bombero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleguardia',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='d', to='bomberos.actividad'),
        ),
        migrations.AlterField(
            model_name='detalleguardia',
            name='guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='d', to='guardias.guardia'),
        ),
    ]
