# Generated by Django 4.1.2 on 2023-05-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bomberos", "0005_alter_actividad_descripcion"),
        ("guardias", "0004_alter_detalleguardia_actividad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleguardia",
            name="actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="guardias",
                to="bomberos.actividad",
            ),
        ),
        migrations.AlterField(
            model_name="detalleguardia",
            name="guardia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="guardias.guardia",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleguardia",
            constraint=models.UniqueConstraint(
                fields=("actividad", "guardia"), name="actividad_guardia_unique"
            ),
        ),
    ]
