# Generated by Django 3.2 on 2024-05-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomberoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.actividad')),
            ],
        ),
        migrations.AlterField(
            model_name='bombero',
            name='rol',
            field=models.CharField(choices=[('1', 'Jefe de Cuerpo'), ('2', 'Administrador')], max_length=1),
        ),
        migrations.RenameModel(
            old_name='Rol',
            new_name='Categoria',
        ),
        migrations.DeleteModel(
            name='RolActividad',
        ),
        migrations.AddField(
            model_name='categoriaactividad',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria'),
        ),
        migrations.AddField(
            model_name='bomberocategoria',
            name='bombero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.bombero'),
        ),
        migrations.AddField(
            model_name='bomberocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria'),
        ),
    ]
