# Generated by Django 3.2 on 2024-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_bombero_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bombero',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='bombero',
            name='rol',
            field=models.CharField(choices=[('1', 'Jefe de Cuerpo'), ('2', 'Administrador'), ('3', 'Bombero')], default='3', max_length=1),
        ),
    ]
