# Generated by Django 4.1.2 on 2023-04-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CodigoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(default='+', max_length=1)),
                ('codigo', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bomberouser',
            name='apellido',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomberouser',
            name='nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField()),
                ('codigoArea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='telefonos', to='bomberos.codigoarea')),
            ],
        ),
        migrations.AddField(
            model_name='bomberouser',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bomberos', to='bomberos.categoriabombero'),
        ),
        migrations.AddField(
            model_name='bomberouser',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bombero', to='bomberos.telefono'),
        ),
    ]
