# Generated by Django 4.1.2 on 2023-04-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0004_actividad_detallecategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
