# Generated by Django 4.1.2 on 2023-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bomberos", "0005_alter_actividad_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomberouser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
