# Generated by Django 4.1.2 on 2023-06-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bomberos", "0006_bomberouser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomberouser",
            name="is_super",
            field=models.BooleanField(default=False),
        ),
    ]
